relative_permalinks: false
highlighter: rouge
markdown: kramdown
permalink: pretty
encoding: UTF-8
include: ["_static", "_sources"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
      author: "hchapman"

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
