relative_permalinks: false
highlighter: pygments
markdown: kramdown
permalink: pretty
include: [projects/pyplcurve/docs/html/_static, projects/pyplcurve/docs/html/_sources]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
      author: "hchapman"
    
