relative_permalinks: false
highlighter: pygments
markdown: kramdown
permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
      author: "hchapman"
    