relative_permalinks: false
highlighter: rouge
markdown: kramdown
permalink: pretty
encoding: UTF-8
include: ["_static", "_sources"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog"
    values:
      layout: "blog"
      author: "hchapman"
  -
    scope:
      path: "_homework"
      type: homework
    values:
      layout: homework
  -
    scope:
      path: "_classwork"
      type: classwork
    values:
      layout: classwork

collections:
  homework:
    output: true
    permalink: /classes/:path/
  classwork:
    output: true
    permalink: /classes/:path/

gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
